# Exercise 0: Introduction to Python

### Use Python as a calculator to compute 256²

In [1]:
256 * 256

65536

### Put the strings "Hello" and "World!" in two variables. Concatenate both Strings and print them

In [3]:
hello = 'Hello'
world = 'World!'
helloworld = hello + world
helloworld

'HelloWorld!'

### Create a list that contains the 4 strings "alpha", "beta", "gamma", and "delta". Add "epsilon" to the end of this list

In [5]:
l = ['alpha', 'beta', 'gamma', 'delta']
l.append('epsilon')
l

['alpha', 'beta', 'gamma', 'delta', 'epsilon']

### Create a sublist with the first three elements of this list


In [6]:
l2 = l[:3]
l2

['alpha', 'beta', 'gamma']

### Write a Python program to construct the following pattern using for loops

In [ ]:
* 
* * 
* * * 
* * * * 
* * * * * 
* * * * 
* * * 
* * 
*

In [8]:
for i in list(range(1,6)) + list(range(4,0,-1)):
  print(i*"*")

*
**
***
****
*****
****
***
**
*


### Write a function that takes 3 input parameters and returns the product of these values

In [11]:
def prod(*a):
  r = 1
  for e in a:
      r *= e
  return r

prod(12,3)

36

### Write a Python function that takes an int as a parameter and checks if the number is prime or not.

In [16]:
def is_prime(a):  
  for i in range(a//2, 1, -1):
    if (a%i==0):
      return False
  return True 

is_prime(7)

True

### Use your function to create a list that contains all primes from 2 to 100

In [17]:
def primes_up_to(x):
  r = []
  for i in range(2,x+1):
    if is_prime(i):
      r.append(i)
  return r

primes_up_to(30)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

### Write a function that simulates dice rolls (6-sided dices)
- Write a function that has the number of dice rolls as the input parameter
- The output is a map with the counts how often each result of a roll (1-6) occurred
- You can use the randomint() function from the random package

In [ ]:
# load the random package
import random

def roll(x):
  result = {1:0, 2:0, 3:0, 4:0, 5:0, 6:0}
  for i in range(1,x):
    y = random.randint(1,6)
    result[y]+=1
  return result

roll(1000000)


{1: 166561, 2: 166531, 3: 166354, 4: 166684, 5: 167081, 6: 166788}

### Combine two dictionaries by adding values for common keys.
d1 = {'a': 100, 'b': 200, 'c':300}

d2 = {'a': 300, 'b': 200, 'd':400}

Sample output: {'a': 400, 'b': 400, 'd': 400, 'c': 300}

In [ ]:
d1 = {'a': 100, 'b': 200, 'c':300}

d2 = {'a': 300, 'b': 200, 'd':400}

def add_dictionaries(d1,d2):
  d = {}
  for k,v in d1.items():
    d[k] = v
  for k,v in d2.items():
    if k in d:
      d[k] += d2[k]
    else: 
      d[k] = d2[k]
  return d

add_dictionaries(d1, d2)

{'a': 400, 'b': 400, 'c': 300, 'd': 400}

### Create a list of lists. Then, write a list comprehension that creates a list with the lengths of each (sub)list in the primary list

In [ ]:
test_l = [[1,2,3],["a", "b"], [123.5, "a", 44]]
[len(t) for t in test_l]

[3, 2, 3]

### Exceptions

Write your own function *my_division* that gets two variables a and b and returns a divided by b. Catch the ZeroDivisionError that occurs if b equals 0 and return 1 in this case.

How could the same behavior be achieved without catching an exception?

In [ ]:
def divide(a,b):
  try:
    return a/b
  except:
    return 1

def divide1(a,b):
  if b == 0:
    return 1
  else: 
    return a/b

print(divide(20,0))
print(divide1(20,0))

1
1


### File handling

Write a function that gets a letter and the path to a (text-)file on your harddrive as input parameters and computes a list as its output. The list should contain one number for each line. The i-th line shows, how often the given letter occurs in line number i in the text file. Test your function on "ftest.txt", which was provided in this exercise!

In [ ]:
def count_letter(letter, filename):
  result = []
  with open(filename, "r") as f: # "r for reading"
    for line in f: 
      result.append(line.count(letter))
    return result

### Change please!
In our currency, we have coins with certain values, e.g., (200,100,50,20,10,5,2,1) cents. Write a function that computes the different options to pay a certain amount X with the given set of coins.

Example:
pay_options (10, [200,100,50,20,10,5,2,1])
[[10],
 [5, 5],
 [5, 2, 2, 1],
 [5, 2, 1, 1, 1],
 [5, 1, 1, 1, 1, 1],
 [2, 2, 2, 2, 2],
 [2, 2, 2, 2, 1, 1],
 [2, 2, 2, 1, 1, 1, 1],
 [2, 2, 1, 1, 1, 1, 1, 1],
 [2, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]

In [ ]:
# slow but simple solution
def pay_options(amount, list_of_coin_values, list_of_used_coins=[]):
  # print(amount, list_of_used_coins_values, list_of_used_coins)
  result = []
  for i, v in enumerate(list_of_coin_values):
    if amount > v:
      new_used_coins = list_of_used_coins.copy()
      new_used_coins.append(v)
      result.extend(pay_options(amount - v, list_of_coin_values[:i], new_used_coins))
    elif amount == v:
      new_options = list_of_used_coins.copy()
      new_options.append(v)
      result.append(new_options)
    return result

## Numpy

In this last set of tasks, you will have to work with numpy, the the fundamental package for scientific computing with Python.
Make sure to execute the cell below to import the package, we will usually use the abbreviation np for numpy to obtain shorter code.

In [ ]:
import numpy as np

### Create a numpy array with 20 rows and 10 columns, where all values are set to zero

In [ ]:
x = np.zeros((20,10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Create an array with the same shape containing all natural numbers 0-199

In [ ]:
np.arange(200).reshape(20,10)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

### Create a 4-dimensional array with exactly 16 elements and set all values to a random integer smaller than 5

In [ ]:
x = np.random.randint(5, size=(2,2,2,2))
x

array([[[[4, 0],
         [0, 3]],

        [[1, 1],
         [3, 2]]],


       [[[0, 3],
         [4, 2]],

        [[1, 4],
         [2, 0]]]])

### What is the mean of all values contained in this array?

In [ ]:
x.mean()

1.875

### Select a sub-array containing exactly two elements of that array!

In [ ]:
x[:,1,1,1]

array([2, 0])

### Given a numpy array, return a new numpy array that contains (only) the elements that are greater than 100

In [ ]:
x = np.array([120,-5,150,250,300,50,112])
x[x > 100]

array([120, 150, 250, 300, 112])